version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "button-event:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  hbase:
    build: ./hbase
    ports:
      - "9090:9090"
      - "9095:9095"
      - "60000:60000"
      - "60010:60010"
      - "60020:60020"
      - "60030:60030"
    environment:
      ZOOKEEPER_QUORUM: zookeeper:2181
    volumes:
      - ./volumes/hbase:/home
      - ./volumes/logs:/opt/hbase/logs

  spark:
    build: ./spark
    ports:
      - "7077:7077"
      - "8080:8080"
      - "4040:4040"
      - "8787:8787"
    depends_on:
      - kafka
      - hbase
    environment:
      ZOOKEEPER_QUORUM: zookeeper:2181
      HBASE_ZOOKEEPER_QUORUM: zookeeper:2181
      KAFKA_BROKER: kafka:9092
      KAFKA_ZOOKEEPER_QUORUM: zookeeper:2181
      HBASE_URL: hbase:9090
    volumes:
      - ./spark/data:/data/csv
      - ./spark/R:/data/R
      - ./spark/python:/data/python
      - ./volumes/spark:/opt/spark/logs
  node:
    build: ./node
    ports:
      - "3000:3000"
    depends_on:
       - hbase
    environment:
      PORT: 3000
      ZOOKEEPER_HOSTNAME: zookeeper
      DEBUG: "*"
    volumes:
      - ./node:/usr/src/app